<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_teaser</name>
   <tag></tag>
   <elementGuidId>19ca06b4-8270-4a42-bc33-b255d4dd9d51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='banner']//div[@id='views_slideshow_cycle_teaser_section_gallery_banner-block_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='banner']//div[@id='views_slideshow_cycle_teaser_section_gallery_banner-block_1']</value>
   </webElementProperties>
</WebElementEntity>
