<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>article</name>
   <tag></tag>
   <elementGuidId>32fb5d77-a1f1-46fe-a53a-86884df54717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//article[@id='article']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//article[@id='article']</value>
   </webElementProperties>
</WebElementEntity>
